### ISSUE TITLE
Tabbar如何直接跳到第二个tab

### ISSUE THREAD

**Issue by whatlife** [kuangshp/react-navigation-demo#2]
TabBar里我如何直接进入到第二个tab的MoveList里呢。
TabBar 有BookList，MoveList，Message，需要怎么设置，才能直接跳转到MoveList？

**Comment by KaelThasWang0919** [comment]
initialRouteName: "", 加上这个属性就可以了

**Comment by whatlife** [comment]
非常感谢！经你提醒现解决了
